auth_enabled: false

server:
  http_listen_port: 3100

distributor:
  ring:
    kvstore:
      store: memberlist
memberlist:
  join_members:
    - loki
ingester:
  lifecycler:
    ring:
      kvstore:
        store: memberlist
      replication_factor: 1
  chunk_idle_period: 3m
  chunk_target_size: 1048576
schema_config:
  configs:
    - from: 2020-10-15
      store: tsdb
      object_store: s3
      schema: v13
      index:
        prefix: index_
        period: 24h
storage_config:
  tsdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/index_cache
    cache_ttl: 24h
  aws:
    endpoint: http://minio:9000
    access_key_id: minioadmin
    secret_access_key: minioadmin123
    s3forcepathstyle: true
    region: us-east-1
    bucketnames: loki-chunks
limits_config:
  ingestion_rate_mb: 200
  ingestion_burst_size_mb: 300
  allow_structured_metadata: true
ruler:
  storage:
    type: s3
    s3:
      bucketnames: loki-rules
      endpoint: http://minio:9000
      s3forcepathstyle: true
      access_key_id: minioadmin
      secret_access_key: minioadmin123
      region: us-east-1
  rule_path: /loki/rules
  alertmanager_url: http://alertmanager:9093